name: animated_search_bar_example
description: Demonstrates how to use the animated_search_bar plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_search_bar:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
